- hosts: private
  become: true
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: latest

    - name: Start and enable Nginx
      service:
        name: nginx
        state: started
        enabled: yes  

    - name: Update package list
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist

    - name: Clean up unused packages
      apt:
        autoremove: yes
        autoclean: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: latest

    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: yes
