- hosts: private
  become: true
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: latest

    - name: Install Docker
      apt:
        name: docker.io
        state: latest

    - name: Start and enable Nginx
      service:
        name: nginx
        state: started
        enabled: yes  

    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: yes
